FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04
ENV PYTHONUNBUFFERED 1

# to be overwritten by .env
ARG NLTK_DATA="set"

RUN apt-get -y update; apt-get -y install curl python3-pip

RUN pip install pip==23.2.1
RUN pip install pip-tools==7.1.0

ADD requirements.txt .
RUN pip-sync requirements.txt 

ADD . .

# fetch and store datasets needed for sentence tokenizer
RUN python3 -c "import nltk;nltk.download('punkt')"